
CREATE TABLE FACT_SALES AS (
SELECT DISTINCT 
  date,
  EXTRACT(YEAR FROM DATE) as year,
  EXTRACT(MONTH FROM DATE) as month,
  EXTRACT(QUARTER FROM DATE) as quarter,
  EXTRACT(DAYOFWEEK FROM DATE) as dayofweek,
  EXTRACT(WEEK FROM DATE) as week,
  CONCAT(EXTRACT(YEAR FROM DATE), EXTRACT(QUARTER FROM DATE)) as year_quarter,
  CONCAT(EXTRACT(YEAR FROM DATE), EXTRACT(MONTH FROM DATE)) as year_month,
FROM `lunar-spring-434419-q4.Analytics.yalo`);