SELECT
    invoice_and_item_number as id,
    date,
    store_number as store_id,
    store_name,
    address,
    city,
    zip_code,
    store_location,
    county_number as county_id,
    county as county_name,
    category as category_id,
    category_name,
    vendor_number as vendor_id,
    vendor_name,
    item_number as item_id,
    item_description,
    pack,
    bottle_volume_ml,
    state_bottle_cost as wholesale_cost,
    state_bottle_retail as selling_price,
    bottles_sold,
    sale_dollars,
    volume_sold_liters,
    volume_sold_gallons
from `lunar-spring-434419-q4.Analytics.yalo`;